version: '3.1'
services:
  db:
    container_name: quiz_db
    image: postgres
    volumes:
      - quiz_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB="quiz"
      - POSTGRES_USER="quiz_user"
      - POSTGRES_PASSWORD="quiz_pass"
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - quiz_net
  web:
    build: .
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - quiz_net
volumes:
  quiz_db: {}
networks:
  quiz_net:
    driver: bridge