version: '3.7'
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=quiz_user
      - POSTGRES_PASSWORD=quiz_pass

  web:
    build: .
    ports:
      - 8080:8080